spring:
  datasource:
    hms:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/hms?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true

logging:
  level:
    org:
      springframework:
        security: info